name: Pylint/Coverage

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pre-commit
        pip install coverage
    - name: PreCommit hooks
      run: |
        pre-commit run --all-files
    - name: Code Coverage
      run: |
        coverage run python/test/test.py
        coverage report
    - name: Analysing the code with pylint
      run: |
        pylint --disable=W --disable missing-docstring python/test/test.py
